import type { Metadata } from "next";
import { Geist_Mono, Instrument_Serif, Raleway, Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { cn } from "@/lib/utils";
import Footer from "@/components/footer";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Finteck - dev+",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "raleway", geistMono.variable, raleway.variable, instrumentSerif.variable, "font-sans", geist.variable)}
    >
      <body className="min-h-screen bg-background text-foreground font-sans">
        <main className="flex min-h-screen flex-col">
          <Navbar />
          {children}
          <Footer/>
        </main>
      </body>
    </html>
  );
}
